<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Create account' => 'Vytvořit účet',
    'Explore' => 'Prozkoumat',
    'Explore places' => 'Prozkoumat místa',
    'Go to profile' => 'Přejít na profil',
    'Open' => 'Otevřít',
    'Register' => 'Registrovat',
    'Search' => 'Hledat',
    'Type city, street or zipcode' => 'Zadejte město, ulici nebo PSČ',
    'and find out which places you liked' => 'a najděte místa, která se vám líbila',
    'and get access to all functions' => 'a získejte přístup ke všem funkcím',
    'and see how the world has changed over time' => 'a podívejte se, jak se svět časem změnil',
];
