<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add new rephoto' => 'Přidat refotografii',
    'Align' => 'Zarovnat',
    'Skip' => 'Přeskočit',
    'Author' => 'Autor',
    'Captured' => 'Zachyceno',
    'Confirm' => 'Potvrdit',
    'Confirm align' => 'Potvrdit zarovnání',
    'Create place' => 'Vytvořit místo',
    'Delete all points' => 'Smazat všechny body',
    'Delete place' => 'Smazat místo',
    'Description' => 'Popis',
    'Edit place' => 'Editovat místo',
    'GPS' => 'GPS',
    'Manual align' => 'Manuální zarovnání',
    'Manual alignment' => 'Manuální zarovnání',
    'Previously uploaded files' => 'Dříve nahrané fotografie',
    'Review' => 'Zkontorlovat',
    'Review alignment' => 'Zkontrolujte zarovnání',
    'Select' => 'Zvolit',
    'Select at least 4 same points by clicking on specific position on one photo and then other. To place marker more accurate click and hold on point to show magnifier glass.' => 'Zvolte alespoň 4 shodné body kliknutím na danou pozici na první a poté na druhé fotografii. K dosažení větší přesnosti použijte kliknutím a podržením lupu.',
    'These images are not aligned and published.' => 'Tyto obrázky nejsou zarovnány a publikovány.',
    'To help you with adding new rephoto, your image was aligned automaticaly with historical photo. Please
                check if this alignment is correct and then continue in upload process by clicking <i>confirm button</i>
                or align photos manually after clicking on <i>manual align</i> button bellow images.' => 'Pokud byl váš obrázek zarovnán automaticky zkontrolujte
                prosím, jestli je zarovnání správné a poté pokračujte nahrání kliknutím na tlačítko <i>potvrdit zarovnání</i>, 
                pokud s výsledkem nejste spokojeni zkuste zarovnat obrázek manuálně pomocí tlačítka <i>manuální zarovnání</i> pod obrázky.',
    'Upload' => 'Nahrát',
    'Upload File' => 'Nahrát soubor',
    'Upload another photo' => 'Nahrát jinou fotografii',
    'Upload new photo of' => 'Nahraje novou fotografii',
    'add to editor' => 'přidat do editoru',
    'delete photo' => 'smazat fotografii',
    'edit photo' => 'upravit fotografii',
    'here or select one of' => 'zde nebo zvolte jednu z',
    'previously uploaded.' => 'dříve nahraných.',
    'remove from editor' => 'odebrat z editoru',
    'Change alignment' => 'Změnit zarovnání',
    'Confirm photo' => 'Potvrzení fotografie',
    'Fill additional photo info and after submitting <a href="#form">form</a>, photo will be visible on place
            page.' => 'Doplňte informace o fotografii a po potvrzení <a href="#form">formuláře</a> bude fotografie viditelná na stránce místa.',
    'Submit' => 'Potvrdit',
];
