<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Back to login' => 'Zpět na přihlášení',
    'Back to page' => 'Zpět na stránku',
    'Edit personal informations' => 'Upravit osobní informace',
    'Favourites' => 'Oblíbené',
    'Forgot password?' => 'Zapoměli jte heslo?',
    'If you are a new user,' => 'Pokud jste nový uživatel,',
    'Log in with Facebook!' => 'Přihlaste se přes Facebook!',
    'Login' => 'Přihlásit se',
    'Login to RePhoto' => 'Přihlaste se do RePhoto',
    'Logout' => 'Odhlásit se',
    'My photos' => 'Moje fotografie',
    'Personal info' => 'Osobní infromace',
    'Register' => 'Registrovat se',
    'Register to RePhoto' => 'Registrujte se do RePhoto',
    'Request new password' => 'Obnovení hesla',
    'Save' => 'Uložit',
    'Send' => 'Odeslat',
    'Set new password' => 'Nastavit nové heslo',
    'Take a look how places has changed in time.' => 'Podívejte se, jak se svět mění.',
    'Unaligned photos' => 'Nezarovnané fotografie',
    'Unpublished photos' => 'Nepublikované fotografie',
    'Uploaded photos' => 'Nahrané fotografie',
    'Welcome to RePhoto' => 'Vítejte na RePhoto',
    'detail' => 'detail',
    'signup here.' => 'registrujte se zde.',
    'email' => '@@email@@',
    'password' => '@@heslo@@',
];
